using System.Collections.Generic;
using System;
using System.Drawing;
using System.Drawing.Imaging;
using System.Runtime.InteropServices;

namespace PictureBox.Image.Testes
{
    public static class ImageFilters
    {
        // Rainbow filter
        public static Bitmap RainbowFilter(Bitmap bmp)
        {
            Bitmap temp = new Bitmap(bmp.Width, bmp.Height);
            int raz = bmp.Height / 4;

            for (int i = 0; i < bmp.Width; i++)
            {
                for (int x = 0; x < bmp.Height; x++)
                {
                    Color originalColor = bmp.GetPixel(i, x);

                    if (i < raz)
                    {
                        temp.SetPixel(i, x, Color.FromArgb(originalColor.R / 5, originalColor.G, originalColor.B));
                    }
                    else if (i < raz * 2)
                    {
                        temp.SetPixel(i, x, Color.FromArgb(originalColor.R, originalColor.G / 5, originalColor.B));
                    }
                    else if (i < raz * 3)
                    {
                        temp.SetPixel(i, x, Color.FromArgb(originalColor.R, originalColor.G, originalColor.B / 5));
                    }
                    else if (i < raz * 4)
                    {
                        temp.SetPixel(i, x, Color.FromArgb(originalColor.R / 5, originalColor.G, originalColor.B / 5));
                    }
                    else
                    {
                        temp.SetPixel(i, x, Color.FromArgb(originalColor.R / 5, originalColor.G / 5, originalColor.B / 5));
                    }
                }
            }
            return temp;
        }

        // Reverting the Rainbow filter
        // CHAT GPT : This method has been generated by asking CHAT GPT to write a class that would revert the effect of the Rainbow Filter
        public static Bitmap RevertRainbowFilter(Bitmap bmp)
        {
            Bitmap temp = new Bitmap(bmp.Width, bmp.Height);
            int raz = bmp.Height / 4;

            for (int i = 0; i < bmp.Width; i++)
            {
                for (int x = 0; x < bmp.Height; x++)
                {
                    Color originalColor = bmp.GetPixel(i, x);
                    int newR = originalColor.R;
                    int newG = originalColor.G;
                    int newB = originalColor.B;

                    if (i < raz)
                    {
                        newR = Math.Min(originalColor.R * 5, 255);
                    }
                    else if (i < raz * 2)
                    {
                        newG = Math.Min(originalColor.G * 5, 255);
                    }
                    else if (i < raz * 3)
                    {
                        newB = Math.Min(originalColor.B * 5, 255);
                    }
                    else if (i < raz * 4)
                    {
                        newR = Math.Min(originalColor.R * 5, 255);
                        newB = Math.Min(originalColor.B * 5, 255);
                    }
                    else
                    {
                        newR = Math.Min(originalColor.R * 5, 255);
                        newG = Math.Min(originalColor.G * 5, 255);
                        newB = Math.Min(originalColor.B * 5, 255);
                    }

                    temp.SetPixel(i, x, Color.FromArgb(newR, newG, newB));
                }
            }
            return temp;
        }

        // Color filter to swap pixel colors
        public static Bitmap SwapFilter(Bitmap bmp)
        {
            Bitmap temp = new Bitmap(bmp.Width, bmp.Height);

            for (int i = 0; i < bmp.Width; i++)
            {
                for (int x = 0; x < bmp.Height; x++)
                {
                    Color originalColor = bmp.GetPixel(i, x);
                    Color swappedColor = Color.FromArgb(originalColor.A, originalColor.G, originalColor.B, originalColor.R);
                    temp.SetPixel(i, x, swappedColor);
                }
            }

            return temp;
        }

        // Reverting the Swap filter
        // CHAT GPT : This method has been generated by asking CHAT GPT to write a class that would revert the effect of the Swap Filter
        public static Bitmap RevertSwapFilter(Bitmap bmp)
        {
            Bitmap temp = new Bitmap(bmp.Width, bmp.Height);

            for (int i = 0; i < bmp.Width; i++)
            {
                for (int x = 0; x < bmp.Height; x++)
                {
                    Color originalColor = bmp.GetPixel(i, x);
                    Color revertedColor = Color.FromArgb(originalColor.A, originalColor.B, originalColor.R, originalColor.G);
                    temp.SetPixel(i, x, revertedColor);
                }
            }
            return temp;
        }
    }
}
